### ISSUE TITLE
Validate sql front matter

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1005]
I got a crash when I (mis)-typed a sql definition:
```
---
sql:
  - presse: ./data/presse.parquet
---

```

because of the leading dash `-` before `presse`, the data structure wasn't as expected and resulted an uncaught error in the console
`Uncaught TypeError: name.split is not a function at FileAttachment (stdlib.js:17:68)`

And some [Object object] appeared in the source code. Lastly, this broke the socket so the page wouldn't update anymore in preview.

This should be caught before, by validating the structure returned by front matter.

**Comment by Fil** [comment]
A different case:

```yaml
---
sql:
  test: []
---
```

results in a crash:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:756:18)
    at tryReadSync (node:fs:432:20)
    at readFileSync (node:fs:486:19)
    at getFileInfo (file:///Users/fil/Source/framework/src/javascript/module.ts:1:2541)
    at getFileHash (file:///Users/fil/Source/framework/src/javascript/module.ts:1:2221)
    at getResolvers (file:///Users/fil/Source/framework/src/resolvers.ts:1:2445)
    at renderPage (file:///Users/fil/Source/framework/src/render.ts:1:729)
    at Server._handleRequest (file:///Users/fil/Source/framework/src/preview.ts:1:5626) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```
