### ISSUE TITLE
yarn dev cannot start app in windows 11 

### ISSUE THREAD

**Issue by liyong357** [observablehq/framework#1053]
I need write some notebook in local computor, so I run `npm init @observablehq` in  command shell。
my code env:
+ window 11
+ node 20.11.1
+ yarn 1.22.22

after `yarn dev`, shell show info:
```bash
yarn run v1.22.22
$ observable preview
Observable Framework v1.3.0
↳ http://127.0.0.1:3000/

GET /
npm:d3-dsv → npm:d3-dsv@3.0.1
npm:@observablehq/plot → npm:@observablehq/plot@0.6.14
npm:d3-dsv@3.0.1/+esm → unable to fetch or parse /_npm/d3-dsv@3.0.1/+esm.js: fetch failed
npm:@observablehq/plot@0.6.14/+esm → unable to fetch or parse /_npm/@observablehq/plot@0.6.14/+esm.js: fetch failed
GET /_observablehq/theme-air,near-midnight.css
GET /_observablehq/client.js
npm:lodash → npm:arquero → npm:apache-arrow → npm:d3 → npm:echarts → npm:htl → npm:leaflet → npm:mapbox-gl → npm:topojson-client → GET /_observablehq/runtime.js
GET /_observablehq/stdlib.js
GET /_npm/d3-dsv@3.0.1/+esm.js
npm:d3-dsv@3.0.1/+esm → npm:topojson-client@3.1.0
npm:apache-arrow@15.0.1
GET /_npm/@observablehq/plot@0.6.14/+esm.js
npm:@observablehq/plot@0.6.14/+esm → npm:leaflet@1.9.4
npm:lodash@4.17.21
npm:mapbox-gl@3.2.0
npm:htl@0.3.1
npm:echarts@5.5.0
npm:d3@7.9.0
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/code/hello-framework/done/node_modules/@observablehq/framework/dist/npm.js:68:22 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7492:28)
      at node:internal/deps/undici/undici:7448:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7478:37)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/code/hello-framework/done/node_modules/@observablehq/framework/dist/npm.js:68:22 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7492:28)
      at node:internal/deps/undici/undici:7448:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7478:37)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

and I run this in wsl, It show the same error info。
```

**Comment by liyong357** [comment]
in wsl, the error info :
```bash
ly@thinkbook15:~/hello-framework$ npm run dev

> dev
> observable preview

Observable Framework v1.3.0
↳ http://127.0.0.1:3000/

GET /
npm:d3-dsv → TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/ly/hello-framework/node_modules/@observablehq/framework/dist/npm.js:193:22 {
  cause: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}
^C^C
ly@thinkbook15:~/hello-framework$ node --version
v20.11.1
ly@thinkbook15:~/hello-framework$ npm --version
10.2.4
ly@thinkbook15:~/hello-framework$
```

**Comment by mbostock** [comment]
This looks like it might be a network problem on your end. Are you able to access cdn.jsdelivr.net?

**Comment by liyong357** [comment]
thank you! @mbostock , your message give me some idea, so I solved my question。
1. I test  https://cdn.jsdelivr.net   in Edge, It's Ok。
2. trace the error log,  It's  a  node api  fetch  errors 。

solve steps  ：
1.  npm i node-fetch
2.  modify file `\node_modules\@observablehq\framework\dist\npm.js`  ， insert line `import fetch from 'node-fetch'`

**Comment by liyong357** [comment]
thank you! @mbostock , your message give me some idea, so I solved my question。 It likes a bug ?
1. I test  https://cdn.jsdelivr.net   in Edge, It's Ok。
2. trace the error log,  It's  a  node api  fetch  errors 。

solve steps  ：
1.  npm i node-fetch
2.  modify file `\node_modules\@observablehq\framework\dist\npm.js`  ， insert line `import fetch from 'node-fetch'`

**Comment by Kiss-World** [comment]
@mbostock  A general issue, but using the method mentioned above didn't solve it."
```> dev
> observable preview

Observable Framework v1.9.0
↳ http://127.0.0.1:3001/

GET /
npm:@observablehq/plot@0.6.15/+esm → src/.observablehq/cache/_npm/@observablehq/plot@0.6.15/_esm.js
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///E:/009_space%E7%A9%BA%E9%97%B4/2024-07-10-%E5%AD%A6%E4%B9%A0%E4%BD%BF%E7%94%A8d3%E5%8F%AF%E8%A7%86%E5%8C%96/hello-framework/node_modules/@observablehq/framework/dist/npm.js:68:22 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8522:28)
      at node:internal/deps/undici/undici:8480:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8509:37)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///E:/009_space%E7%A9%BA%E9%97%B4/2024-07-10-%E5%AD%A6%E4%B9%A0%E4%BD%BF%E7%94%A8d3%E5%8F%AF%E8%A7%86%E5%8C%96/hello-framework/node_modules/@observablehq/framework/dist/npm.js:68:22 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8522:28)
      at node:internal/deps/undici/undici:8480:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8509:37)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}```
