### ISSUE TITLE
Arquero import fails

### ISSUE THREAD

**Issue by ae3e** [observablehq/framework#1285]
When trying to use Arquero in a separate file that could be imported (with local import) both in data loaders and notebooks, the following import doesn't compile for notebooks :

```js
import * as aq from 'arquero'; //I thought it could be used since version 1.6
//Using npm import works for notebooks
//import * as aq from 'npm:arquero';
```

Here is the error :

```batch
arquero → docs\.observablehq\cache\_node\arquero@5.4.0\index.js
Error [RollupError]: Expected ';', '}' or <eof>
    at getRollupError (file:///C:/xxxx/observable/dashboards/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    ... 4 lines matching cause stack trace ...
    at async ModuleLoader.addModuleSource (file:///C:/xxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/node-entry.js:18729:13) {
  cause: Error [RollupError]: Expected ';', '}' or <eof>
      at getRollupError (file:///C:/xxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
      at ParseError.initialise (file:///C:/xxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/node-entry.js:11170:28)
      at convertNode (file:///C:/xxxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/node-entry.js:12915:10)
      at convertProgram (file:///C:/xxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/node-entry.js:12232:12)
      at Module.setSource (file:///C:/xxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/node-entry.js:14076:24)
      at async ModuleLoader.addModuleSource (file:///C:/xxxxx/observable/dashboards/node_modules/rollup/dist/es/shared/node-entry.js:18729:13) {
    code: 'PARSE_ERROR',
    pos: 10
  },
```

Thanks for your help

**Comment by mbostock** [comment]
I suspect this is because arquero imports `package.json` and this is fixed in main but not yet released.

Note that you can use `npm:arquero` instead and there import will work.

**Comment by mbostock** [comment]
[1.7 is released.](https://github.com/observablehq/framework/releases/tag/v1.7.0) Please try upgrading and let us know if that fixed the problem for you!
