### ISSUE TITLE
Missing deckgl package.

### ISSUE THREAD

**Issue by FilipByren** [observablehq/framework#1877]
# Issue with `deck.gl` Visualizations in Observable Framework

## Problem
The `deck.gl` visualizations in the Observable Framework do not work locally out of the box.

---

## Steps to Reproduce
1. Clone the repository.
2. Run:
   ```bash
   npm install
   npm run dev
```
3.	Visit: http://127.0.0.1:3000/lib/deckgl.

## Proposed Fix

Install deck.gl as a dependency:
```bash
npm install deck.gl
```

## Remaining Problem

Even after the fix, using deck.gl in custom apps with @observablehq/framework may still result in the following error (even after install deck.gl):
```
Protocol error Error: Not found: /lib/deckgl
    at enoent (file:///Users/....../node_modules/@observablehq/framework/dist/error.js:14:24)
    at LoaderResolver.loadPage (file:///Users/...../node_modules/@observablehq/framework/dist/loader.js:55:13)
    at hello (file:///Users/..../node_modules/@observablehq/framework/dist/preview.js:349:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebSocket.<anonymous> (file:///Users/..../node_modules/@observablehq/framework/dist/preview.js:372:11) {
  code: 'ENOENT'
}
```

Hope this fix + updating my app using @observablehq/framework will resolve that issue

**Comment by FilipByren** [comment]
Happy to fix it but lack the access rights.

**Comment by FilipByren** [comment]
Im wrong, missed this layer:

const topo = import.meta.resolve("npm:visionscarto-world-atlas/world/50m.json");
const world = fetch(topo).then((response) => response.json());
const countries = world.then((world) => topojson.feature(world, world.objects.countries));
