### ISSUE TITLE
Bug: `Error: File './.svelte-kit/tsconfig.json' not found.`

### ISSUE THREAD

**Issue by palewire** [observablehq/framework#847]
I cloned a deployed framework repository, created on a Linux desktop, to a Macbook laptop. When I tried to install it and `npm run dev`, I got this error:

```bash
Error: File './.svelte-kit/tsconfig.json' not found.
    at Ae (file:///Users/U6122976/Code/newsapps_push-alert-archive/site/node_modules/get-tsconfig/dist/index.mjs:3:9087)
    at te (file:///Users/U6122976/Code/newsapps_push-alert-archive/site/node_modules/get-tsconfig/dist/index.mjs:3:10051)
    at ie (file:///Users/U6122976/Code/newsapps_push-alert-archive/site/node_modules/get-tsconfig/dist/index.mjs:3:10757)
    at $e (file:///Users/U6122976/Code/newsapps_push-alert-archive/site/node_modules/get-tsconfig/dist/index.mjs:3:10862)
    at file:///Users/U6122976/Code/newsapps_push-alert-archive/site/node_modules/tsx/dist/esm/index.mjs:1:1521
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async file:///Users/U6122976/Code/newsapps_push-alert-archive/site/node_modules/@observablehq/framework/bin/observable-init.js:3:1

Node.js v20.11.1
```

**Comment by mbostock** [comment]
This looks like a bug in `tsx` so not sure there’s much we can do. Though I think we’ll probably need to drop our dependency on `tsx` at runtime and just use it for development. That will allow us to support Node 18 too…

I would try deleting that file and running it again, assuming you don’t actually need it for something.
