### ISSUE TITLE
import.meta.resolve("observablehq:minisearch.json") errors

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#948]
To reproduce:

```sh
git clone git@github.com:observablehq/framework.git meta
cd meta
echo '```js\nimport.meta.resolve("observablehq:minisearch.json")\n```\n' > docs/meta.md
yarn && yarn build

...
build src/client/minisearch.json →
Unexpected error: Could not resolve entry module "src/client/minisearch.json".
```

running `yarn build --debug` gives details:

```
RollupError: Could not resolve entry module "src/client/minisearch.json".
    at error (file:///Users/fil/Source/meta/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.loadEntryModule (file:///Users/fil/Source/meta/node_modules/rollup/dist/es/shared/node-entry.js:17990:20)
    at async Promise.all (index 0)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is building the docs, so the search option is on. It's a clean repo. I've seen the same error in CI (running the project on vercel).

If I `touch src/client/minisearch.json` the site builds correctly, and `dist/meta.html` points to the correct file:
```js
…
define({id: "37bc78c5", inputs: ["display"], body: async (display) => {
display(await(
new URL("./_observablehq/minisearch.8cf337bc.json", location).href
))
}});
```

but then I have a spurious empty file in the build:
```sh
❯ ls -al dist/_observablehq/minisearch.*
-rw-r--r--@ 1 fil  staff  136784  2 mar 10:28 dist/_observablehq/minisearch.8cf337bc.json
-rw-r--r--@ 1 fil  staff       1  2 mar 10:28 dist/_observablehq/minisearch.json

```

**Comment by mbostock** [comment]
It works in preview, just not in build. Investigating…
