### ISSUE TITLE
yarn highlight.js --> highlight.ts results in undeclared dependency error

### ISSUE THREAD

**Issue by cameronraysmith** [observablehq/framework#958]
Attempting to use the create script with yarn as package manager, via either npm or yarn, appears to attempt to convert `highlight.js` imports into `hightlight.ts`, which is not a valid dependency

<details><summary>yarn create highlight.ts undeclared</summary>

```bash
❯ yarn create @observablehq
➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @observablehq/create@npm:1.0.0, @clack/core@npm:0.3.4, @clack/prompts@npm:0.7.0, @esbuild/aix-ppc64@npm:0.19.12, @esbuild/android-arm64@npm:0.18.20, @esbuild/android-arm64@npm:0.19.12, @esbuild/android-arm@npm:0.18.20, @esbuild/android-arm@npm:0.19.12, and 306 more.
➤ YN0000: └ Completed in 1s 145ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 259 packages were added to the project (+ 48.9 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ esbuild@npm:0.19.12 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 818ms
➤ YN0000: · Done with warnings in 2s 116ms


/private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.pnp.cjs:8518
  return Object.defineProperties(new Error(message), {
                                 ^
Error: @observablehq/framework tried to access highlight.ts, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: highlight.ts (via "highlight.ts/package.json")
Required by: @observablehq/framework@npm:1.0.0 (via /private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.yarn/cache/@observablehq-framework-npm-1.0.0-36b9b0de75-c00d2df9a2.zip/node_modules/@observablehq/framework/src/markdown.ts)

    at makeError (/private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.pnp.cjs:8518:34)
    at resolveToUnqualified (/private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.pnp.cjs:10166:21)
    at Object.resolveToUnqualified (/private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.pnp.cjs:10346:26)
    at resolve$1 (file:///private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.pnp.loader.mjs:1993:31)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at l (file:///private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.yarn/cache/tsx-npm-4.2.1-8e1653b737-7da00dfbbc.zip/node_modules/tsx/dist/esm/index.mjs:13:36)
    at O (file:///private/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/xfs-d1e4cfdd/dlx-1436/.yarn/cache/tsx-npm-4.2.1-8e1653b737-7da00dfbbc.zip/node_modules/tsx/dist/esm/index.mjs:13:1062)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
```

</details> 

For v1.0.0 the error above occurs here
https://github.com/observablehq/framework/blob/6db4a856fb171a4ccfa13ec7b5a2f8d22be8ed53/src/markdown.ts#L6

If we install from main then the same error occurs here
https://github.com/observablehq/framework/blob/1ea7ff1e08e56f77efa3bbe9b5bc99d58f25e06f/src/html.ts#L3

<details><summary>environment</summary>

```bash
❯ yarn --version
4.1.0
❯ node --version        
v21.6.2
❯ npm --version         
10.5.0
```

also tested with

yarn 3.8.0 and 3.7.0

</details>

**Comment by mbostock** [comment]
Hmm, I haven’t tried the latest version of yarn. We use Yarn Classic here. I can see if I can reproduce, but this sounds like another tsx problem which we are planning on removing #850.

**Comment by cameronraysmith** [comment]
This may very well be a yarn as opposed to framework issue. Just wanted to report here for ux feedback. Many thanks!

**Comment by cameronraysmith** [comment]
I will close this as presumably outside the scope of framework, but feel free of course to manage as relevant.

**Comment by mbostock** [comment]
I’ve confirmed that Framework doesn’t work with Yarn 4.x (due to tsx incompatibilities, it appears). I’ll test again when #850 is fixed.

**Comment by mbostock** [comment]
I’ve confirmed Yarn Berry works in the latest release 1.1.2. Thanks for the feedback and please let us know if you run into any other issues!

**Comment by cameronraysmith** [comment]
Thank you!
